### ISSUE TITLE
使用你提供的GitHub Pages

### ISSUE THREAD

**Issue by liao-can-jie** [Demo-Liu/FreeServer#12]
java.net.UnknownHostException: demo-ad.github.io
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
	at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.ff.postpone.common.CommonCode.isInitBlog(CommonCode.java:137)
	at com.ff.postpone.task.Postpone.postpone(Postpone.java:81)
	at com.ff.postpone.task.Postpone.executeInternal(Postpone.java:34)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2020-09-04 11:30:30.255 ERROR 8820 --- [eduler_Worker-1] com.ff.postpone.task.Postpone            : 阿贝云账号: 15359571908,,延期过程出错!!!

Process finished with exit code -1

**Comment by liao-can-jie** [comment]
没问题了，我设置了hosts

**Comment by 12123ads** [comment]
这个咋解决的，我也遇到了一样的问题

**Comment by 12123ads** [comment]
@liao-can-jie 这个咋解决的，我也遇到了一样的问题
